#!/bin/bash

function error_exit
{
    echo "$1" 1>&2
    exit 1
}

# Check if commit message argument
if [ -z "$1" ]
then
  echo "deploy script error: What changes did you make? Type a commit message."
  exit 1
fi

grunt --force
git add -A
git commit -m "$1" || error_exit "deploy script error: no changes to commit"
git push origin master
git checkout gh-pages
git merge master
git push origin gh-pages
git checkout master
